### ISSUE TITLE
Contribute to Julia's conference paper on ECAs work

### ISSUE THREAD

**Issue by raquelalegre** [UCL-ShippingGroup/shipviz#34]
Write some info on CartoDB and QGIS, why those were chosen and how I used them for the ECAs use case.

Deadline is 23rd Oct.

**Comment by juliaschaumeier** [comment]
Here is the LaTeX document (for now saved as txt)  for the tools section, which we can then call from the main text body: 
[SectionTools.txt](https://github.com/UCL-ShippingGroup/shipviz/files/20091/SectionTools.txt)

**Comment by raquelalegre** [comment]
Andrew Hill himself replied to my question about citing CartoDB:

```
We don't have a publication to cite at this time. However, you can cite the GitHub repo (https://github.com/CartoDB/cartodb/) and the current version number (https://github.com/CartoDB/cartodb/blob/master/package.json#L2)

Cheers,
A
```

I also found [this](http://hub.qgis.org/projects/quantum-gis/wiki/QGIS_Citation_Repository) about citing QGIS.

```
<pre>
  @Manual{QGIS_software,
    title = {QGIS Geographic Information System},
    author = {{QGIS Development Team}},
    organization = {Open Source Geospatial Foundation},
    year = {2009},
    url = {http://qgis.osgeo.org},
  }
</pre>

```

Still working on my bit!

**Comment by raquelalegre** [comment]
Some drafts can be found [here](https://github.com/UCL-ShippingGroup/shipviz/tree/master/doc).

**Comment by raquelalegre** [comment]
Submitted! We can rest now.
